version: '3.10'
services:
  clothing-model:
    image: zc-10-model:xception-v4-001
  gateway:
    image: zc-10-gateway:002
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - 9696:9696